### ISSUE TITLE
Why only the CNN backbone is used in testing?

### ISSUE THREAD

**Issue by vinhtq115** [dustin-nguyen-qil/SEMI_VCCReID#1]
Hello. In the section 4.2 "Implementation details" of your paper, you wrote that:

> In testing stage, we applied the same sampling strategy on both datasets to form 8-frame input clips. The input clip is passed to the trained CNN backbone only, then the output frame-wise feature set is averaged as the video- wise person representation, which is then used to compute pair-wise similarities for matching stage.

Could you explain why in testing stage, only the CNN backbone is used but not other modules like TSM, texture branch, etc.?

Thank you.

**Comment by dustin-nguyen-qil** [comment]
This is to save computational cost in inference. TSM is only used in training to assist and enhance the robustness of the CNN backbone in texture branch.

**Comment by vinhtq115** [comment]
> This is to save computational cost in inference. TSM is only used in training to assist and enhance the robustness of the CNN backbone in texture branch.

I see. Thank you.

**Comment by kb1ooo** [comment]
@dustin-nguyen-qil Did you look at accuracy if you used the full feature vector including the shape component?  In spite of computational cost, perhaps it would still be useful in a forensic setting.

**Comment by vinhtq115** [comment]
@kb1ooo seems like the accuracy drops if shape features are also used. 
![shape](https://github.com/user-attachments/assets/a072be87-22d1-4f99-813a-a498e9deb2cb)
