### ISSUE TITLE
prepare.py

### ISSUE THREAD

**Issue by Dererror** [dustin-nguyen-qil/SEMI_VCCReID#2]
I'm running "python datasets/prepare. Py - root"/media/dustin/DATA/Research/Video - -based ReID "-- dataset_name VCCR", The prompt is that the prepare. py file is not found.Could you please provide me with this file?

**Comment by dustin-nguyen-qil** [comment]
I will update the code. You can also find the prepare.py file [here](https://github.com/dustin-nguyen-qil/VCCReID-Baseline/blob/main/datasets/prepare.py)

**Comment by Dererror** [comment]
> 我将更新代码。您也可以[在此处](https://github.com/dustin-nguyen-qil/VCCReID-Baseline/blob/main/datasets/prepare.py)对 prepare.py 文件进行罚款
I ran it successfully, thank you

**Comment by dustin-nguyen-qil** [comment]
If possible, please help me star this repo and also [this baseline repo](https://github.com/dustin-nguyen-qil/VCCReID-Baseline). Would appreciate it. Thanks
